config/routes.rb
Pulsar::Application.routes.draw do

  devise_for :users
  
  match '/home' => 'pages#home'
  match '/admin' => 'pages#administration'
  match '/sumary' => 'pages#sumary'
  match '/exams' => 'pages#exams'
  match '/userpanel/:user_id' => 'pages#userpanel'

  resources :users do
    resource :profile
    resources :evaluations do
      resources :details
    end
    resources :postural_assessments
    resources :exams
  end

  root to: 'pages#home'
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable #, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
	attr_accessible :username, :email
	validates_presence_of :username, message: "Digite um nome de usuário válido"
	validates_presence_of :email, message: "Digite um email válido"

	has_one :profile
	has_many :evaluations
  has_many :postural_assessments
  has_many :goals
  has_many :exams
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			redirect_to(new_user_profile_path(@user), :notice => "Usuário criado com sucesso")
		else
			render :action => "new"
		end
	end

	def show
		@user = User.find(params[:id])
		if !@user.profile.blank?
			@profile = @user.profile	
		end		
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user])
			redirect_to(@user, :notice => 'Usuário modificado com sucesso!')
		else
			render :action => "edit"
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_url
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="errorExplanation">
		<h2><%= pluralize(@user.errors.count, "error") %> impediu este usuário de ser salvo:</h2>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>
	</ul>
	</div>  


	<div class="field">
		<%= f.label :username, "Nome de Usuário" %>
		<%= f.text_field :username %>
	</div>
	<div class="field">
		<%= f.label :email, "Email" %>
		<%= f.text_field :email %>
	</div>
	<div class="actions">
		<%= f.submit "Enviar", disable_with: 'Enviando...' %>
	</div>

<% end %>

app/views/users/edit.html.erb
<h1>Editando Usuário</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @user %>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Nome de usuário:</b>
	<%= @user.username %>
</p>
<p>
	<b>Email:</b>
	<%= @user.email %>
</p>

<%= link_to 'Editar', edit_user_path(@user)  %>
<% if @profile.blank? %>
	<%= link_to 'Criar Perfil', new_user_profile_path(@user) %>
<% else %>
	<%= link_to 'Editar Perfil', user_profile_path(@user) %>
<% end %>