config/routes.rb
Pulsar::Application.routes.draw do

  devise_for :users
  
  match '/home' => 'pages#home'
  match '/admin' => 'pages#administration'
  match '/sumary' => 'pages#sumary'
  match '/exams' => 'pages#exams'
  match '/userpanel/:user_id' => 'pages#userpanel'

  resources :users do
    resource :profile
    resources :evaluations do
      resources :details
    end
    resources :postural_assessments
    resources :exams
  end

  root to: 'pages#home'
end

app/views/pages/administration.html.erb
<h1>Sistema Viva Bem!</h1>


<% if current_user.try(:admin?) %>
	<h3>Olá <%= current_user.username%>!</h3>
	<p>Você é um dos administradores do sistema! Nesta página, você poderá acessar, editar e excluir todos os usuários, inclusive o seu. Você também poderá ceder direitos de administrados para outros usuários.</p>
	<p>Lembre-se: Com grandes poderes vêm grandes responsabilidades.</p>

<% if !@users.blank? %>
  <% for user in @users %>
	<p>Usuário: <%= user.username %>  |  Email: <%= user.email%>  |  <%= user.profile.blank? ? "Sem Perfil" : (link_to "Perfil", user_profile_path(user)) %>  |  Admnistrador? <%= user.admin? ? "Sim" : "Não" %>  |  <%= link_to "Editar", edit_user_path(user) %> %></p>    
  <% end %>
<% else %>
 	 <p>Nenhum usuário cadastrado foi encontrado!</p>
<% end %>

<% else %>
	<h1>Erro 403: Acesso negado!</h1>
	<p>Você não deveria estar aqui! Clique <%= link_to 'aqui', :back %> para voltar!</p>
<% end %>

app/views/pages/details.html.erb
<h1>Sistema Viva Bem!</h1>

<h2>Detalhes do Seu Corpo</h2>
	<p class="justified">Aqui estão registradas suas lesões e detalhes crônicos, caracteristicos do seu corpo.</p>
	<p class="justified">Em nosso sistema, chamamos de "Detalhes" todas as lesões e detalhes dignos de observação notados em cada avaliação.</p>
	<p class="justified">Cores <b>claras</b> correspondem a detalhes <b>crônicos</b>, ou seja, mais persistentes, que estarão presentes por mais tempo, enquanto detalhes mais <b>escuros</b> representam detalhes <b>imediatos</b>, detectados em avaliações individuais e que, com o tempo, desaparecerão ou serão substituídos por outros detalhes.</p>
	<h3>Últimas Marcações</h3>
	<p class="justified">Essa é uma lista rápida dos últimos detalhes cadastrados no nosso sistema:</p>
	<% if !@details_all.blank? %>
	  <% for item in @details_all %>
	    <b>Área do Detalhe:</b> <%= detail_message(item.area) %> <br>
	    <b><%= item.title %></b> <br>
	    <p><b>Observações: </b><%= item.description %></p>
	    <p>Trata-se de <%= item.tipo == 1 ? "uma lesão" : "uma marcação de detalhe"%> <%= (item.cronico && (item.tipo == 1)) ? "crônica" : "" %> <%= (item.cronico && !(item.tipo == 1)) ? "crônico" : "" %></p> <br>
	  <% end %>
	<% else %>
		nope
	<% end %>

app/views/pages/exams.html.erb
<h1>Sistema Viva Bem!</h1>

<h2>Sua Saúde Hoje</h2>
	<p class="justified">Aqui você verá uma comparação rápida entre seus exames disponíveis, com dicas importantes quanto aos seus resultados.</p>

<% if @exams.size == 2 %>
	<h3>Comparação de Exames</h3>
	<p class="justified">Como você já possui ao menos 2 exames cadastrados conosco, podemos fazer uma comparação rápida quanto a sua evolução desde que você se juntou à nossa academia:</p>
	<p><b>Exame mais atual: <%= @exams.last.dataexame%></b> | <b>Exame antigo: <%= @exams.first.dataexame%></b></p>
	<p><b>Lembre-se: Esses são exames complementares e nunca substituirão a avaliação de um médico. Todas as informações abaixo devem ser encaradas como dicas e não como orientação médica adequada.</b></p><br>
	<b>Colesterol</b>
	<% if @colesterol_valor != 0 %>
		<p>De acordo com seu último exame, seu <b>Colesterol Total</b> está <%= @colesterol_mensagem %> do valor recomendado de acordo com sua idade, com o valor de <%= @colesterol_total%>mg/dl. Você <%= @colesterol_diferenca > 0 ? "ganhou" : "perdeu" %> <%= @colesterol_diferenca.abs %>mg/dl de colesterol entre seus últimos exames!</p>
	<% else %>
		<p>Seu colesterol não pode ser calculado. Clique <%= link_to "aqui", new_user_profile_path(@user) %> para criar seu perfil para que tenhamos dados o suficiente para fazer os cálculos!</p>
	<% end %>
	<p class="justified">De acordo com a Sociedade Americada do Coração (AHA), os seus indices de HDL (o chamado colesterol bom) estão <%= @hdl_mensagem%>. Você <%= @hdl_comparativo > 0 ? "ganhou" : "perdeu" %> colesterol bom entre seus últimos exames, ficando com <%= @user.exams.last.hdl%>mg/dL em seu último exame!</p>
<% else %>
	
<% end %>

app/views/pages/home.html.erb
<h1>Sistema Viva Bem!</h1>

<% if user_signed_in? %>
	<h2>Bem vindo, <%= current_user.username %>!</h2>
	<p class="justified"> Este é o Sistema Viva Bem, um monitor digital de sua saúde. Nestas páginas você encontrará informações preciosas
		quanto às suas avaliações físicas, exames e toda a sua evolução física desde a sua primeira corrida na esteira da
		Pulsar Studio Fitness! </p>
	<% if current_user.profile.blank? %>
		<p>Você não possui um perfil ainda! <%= link_to 'Crie seu perfil agora!', new_user_profile_path(current_user) %></p>
	<% else %>
		<p>Seu perfil está completo!</p>
		<p><%= link_to 'Veja', user_profile_path(current_user) %> ou <%= link_to 'edite', edit_user_profile_path(current_user) %> seu Perfil!</p>
	<% end %>
<% else %>
	<h2>Bem Vindo! Você não está logado!</h2>
	<%= link_to "Registrar", new_user_registration_path %> |
	<%= link_to "Entrar", new_user_session_path %>
<% end %>

app/views/pages/postural.html.erb
<h1>Sistema Viva Bem!</h1>

<h2>Sua Postura</h2>
<p class="justified">Aqui você verá detalhes relacionados à sua última avaliação postural, com uma rápida análise e descrição de eventuais problemas posturais.</p>

<p>Foram marcados os seguintes problemas posturais:</p>

<% if !@postural_assessment.blank? %>
	<% if @postural_assessment.cifose %>
		<h3>Alteração de Cifose</h3>
		<p><%= image_tag("Cifose.jpg", alt: "Cifose", class: "postura") %><br> <br> Alterações na cifose da coluna levam a uma queda dos ombros e, em casos mais extremos, no que é chamado de corcundismo. Com a ajuda de exercícios específicos, é possível reduzir a alteração e melhorar tanto a postura quanto a qualidade de vida do paciente.</p>

	<% end %><br><br><br><br>
	<% if @postural_assessment.lordose %>
		<h3>Alteração de Lordose</h3>
		<p><%= image_tag("Lordose.jpg", alt: "Lordose", class: "postura") %><br> <br> Alterações significativas na curva lordótica da coluna podem tornar as nadegas mais proeminentes e, ao ficar deitado de costas, o aluno perceberá a existência de algum espaço entre sua coluna e o chão. Problemas mais graves geralmente são tratados na infância, mas desvios menores não são incomuns entre adultos.</p><br><br>
	<% end %>
	<% if @postural_assessment.escoliose %>
		<h3>Alteração de Escoliose</h3>
		<p><%= image_tag("Escoliose.jpg", alt: "Escoliose", class: "postura") %><br> <br> Uma alteração relacionada à lordose implica em um desvio lateral na coluna (notado tanto na visão frontal quanto das costas do aluno), resultando a grosso modo em um formato de "S" na coluna.</p>
	<% end %><br><br><br><br><br><br>
	<% if @postural_assessment.artrose %>
		<h3>Artrose</h3>
		<p><%= image_tag("artrose.jpg", alt: "Artrose", class: "postura") %><br> <br> A figura ao lado mostra uma comparação entre uma coluna saudável (marcada em azul) e uma coluna com artrose (em vermelho): O desgaste da cartilagem da região leva a inflamação do tecido, o que causa atrito e dores na coluna.</p>
	<% end %><br><br><br><br>
	<% if @postural_assessment.hernia %>
		<h3>Hérnia de Disco</h3>
		<p><%= image_tag("Hernia.jpg", alt: "Hérnia", class: "postura") %>A hérnia de disco é caracterizada pelo deslocamento ou lesão de um ou mais discos (marcado em azul) da coluna. Pode diminuir a flexibilidade da coluna e causar muita dor.</p>
	<% end %><br><br>

<% else %>
  
<% end %>

app/views/pages/sumary.html.erb
<h1>Sistema Viva Bem!</h1>

<h2>Sua Saúde Hoje</h2>
	<p class="justified">Nesta seção você poderá criar metas e fazer uma comparação rápida entre a sua evolução nas últimas duas avaliações físicas</p>

<% if @evaluations.size == 2 %>
	<h3>Comparação de Avaliações</h3>
	<p class="justified">Você já possui mais de uma avaliação conosco e, portanto, podemos realizar uma comparação rápida entre os seus resultados em uma e em outra avaliação:</p>
	<p><b>Última Avaliação: <%= @evaluations.last.dataeval%></b> | <b>Penultima Avaliação: <%= @evaluations.first.dataeval%></b></p>
	<p><b>Peso:</b> Você estava com <%= @evaluations.first.peso%>kg na primeira avaliação e <%= @evaluations.last.peso%>kg na última avaliação! <% if @evaluations.first.peso < @evaluations.last.peso %> Você conseguiu perder <%= @evaluations.first.peso.to_i-@evaluations.last.peso.to_i%>kg!<% end %></p>
	<p><b>Percentual de Gordura:</b> <% if @evaluations.first.pgordura > @evaluations.last.pgordura %> Você conseguiu perder <%= @evaluations.first.pgordura-@evaluations.last.pgordura %> de percentual de gordura, ficando com <%= @evaluations.last.pgordura %>%!
	<% else %> Você ganhou <%= @evaluations.last.pgordura-@evaluations.first.pgordura %> de percentual de gordura, ficando com <%= @evaluations.last.pgordura %>%, podemos melhorar isso!<% end %></p>
	<p><b>Indice de Massa Corporal: </b>Você está <%= @imc_message %> Seu último IMC cálculado é <%= @evaluations.last.imc %>!</p>
<% elsif @evaluations.size == 1%>
	<h3>Última Avaliação</h3>
	<p class="justified">Você não possui avaliações o suficiente para comparamos seu desempenho, mas aqui estão alguns dados interessantes sobre a sua última avaliação:</p>
	<p><b>Última Avaliação: <%= @evaluations.last.dataeval%></b></p>
	<p><b>Peso:</b> Você estava com <%= @evaluations.last.peso%> nesta avaliação.
	<p><b>Percentual de Gordura:</b> Você tinha <%= @evaluations.first.pgordura %>% de gordura em seu corpo.
	<p><b>Indice de Massa Corporal: </b>Você está <%= @imc_message %> Seu último IMC cálculado é <%= @evaluations.last.imc %>!</p>
	<% else %>
	<p class="justified">Você ainda não possui nenhuma avaliação para compararmos seus resultados! Fale com nossa equipe e agende uma avaliação, ou clique <%= link_to "aqui", new_user_evaluation_path(@user) %> para criar uma nova avaliação!</p>
<% end %>

<h3>Metas</h3>
<p class="justified">Aqui você pode verificar suas últimas metas, prometidas em suas últimas avaliações! Utilize-as para guia-lo em seu treino.</p>
<% if !@metas.blank? %>
  <% @metas.each do |item| %>
    <p><b>Meta:</b><%= item.name %></p>
  <% end %>
<% else %>
  <p>Você ainda não possui nenhuma meta.</p>
<% end %>

app/views/pages/userpanel.html.erb
<h1>Sistema Viva Bem!</h1>


<% if current_user.try(:admin?) %>
	<h3>Olá <%= current_user.username%>!</h3>
	<p>Você é um dos administradores do sistema! Este é o painel de admnistração do usuário <%= @user.username %>. Aqui você poderá verificar os exames e as avaliações deste usuário, além de poder editá-los e eventualmente excluí-los.</p>
	<p>Lembre-se: Com grandes poderes vêm grandes responsabilidades.</p>

<% if !@user.blank? %>
  	<p>Usuário: <%= @user.username %>  |  Email: <%= @user.email%>  |  <%= @user.profile.blank? ? "Sem Perfil" : (link_to "Perfil", user_profile_path(@user)) %>  |  <%= link_to "Editar Usuário", edit_user_path(@user) %> </p>

  	<h3>Avaliações Físicas do Usuário:</h3>    
  	<% if !@user.evaluations.blank? %>
  	  <% for evaluation in @user.evaluations.last(3) %>
  	    <b>Data da Avaliação:</b>
		<%= evaluation.dataeval %> <%= link_to "Ver", user_evaluation_path(@user,evaluation) %> | <%= link_to "Editar", edit_user_evaluation_path(@user,evaluation)%><br>	
  	  <% end %>
  	  <%= link_to "Nova avaliação física", new_user_evaluation_path(@user) %> | 
  	  <%= link_to "Todas as avaliações físicas", user_evaluations_path(@user) %>
  	<% else %>
  	  <p>Não há avaliações recentes!</p>
  	  <%= link_to "Nova avaliação física", new_user_evaluation_path(@user) %>
  	<% end %>

  	<h3>Avaliações Posturais</h3>

  	<% if !@user.postural_assessments.blank? %>
  	  <% for item in @user.postural_assessments.last(3) %>
  	    <b>Data da Avaliação:</b>
		<%= item.dataeval %> <%= link_to "Ver", user_postural_assessments_path(@user,item) %> | <%= link_to "Editar", edit_user_postural_assessment_path(@user,item)%><br>	
  	  <% end %>
  	  <%= link_to "Nova avaliação postural", new_user_postural_assessment_path(@user) %> | 
  	  <%= link_to "Todas as avaliações posturais", user_postural_assessments_path(@user) %>
  	<% else %>
  	  <p>Não há avaliações recentes!</p>
  	  <%= link_to "Nova avaliação postural", new_user_postural_assessment_path(@user) %>
  	<% end %>

  	<h3>Exames Clínicos</h3>

  	<% if !@user.exams.blank? %>
  	  <% for item in @user.exams.last(3) %>
  	    <b>Data do Exame:</b>
		<%= item.dataexame %> <%= link_to "Ver", user_exams_path(@user,item) %> | <%= link_to "Editar", edit_user_exam_path(@user,item)%><br>	
  	  <% end %>
  	  <%= link_to "Novo exame clínico", new_user_exam_path(@user) %> | 
  	  <%= link_to "Todos os exames clínicos", user_exams_path(@user) %>
  	<% else %>
  	  	<p>Não há exames recentes!</p>
  	  	<%= link_to "Novo exame clínico", new_user_exam_path(@user) %>
  	<% end %>

<% else %>
 	 <h1>Erro 500: Algo está MUITO errado.</h1>
 	 <p>Você não deveria encontrar este erro ou chegar a esta página da forma em que chegou! Nossos administradores foram informados do problema! Clique <%= link_to 'aqui', :back %> para voltar e tentar novamente! Se o erro persistir, entre em contato!</p>
<% end %>

<% else %>
	<h1>Erro 403: Acesso negado!</h1>
	<p>Você não deveria estar aqui ou não possui privilégios o suficiente para acessar essa página! Clique <%= link_to 'aqui', :back %> para voltar!</p>
<% end %>