config/routes.rb
Pulsar::Application.routes.draw do

  devise_for :users
  
  match '/home' => 'pages#home'
  match '/admin' => 'pages#administration'
  match '/sumary' => 'pages#sumary'
  match '/exams' => 'pages#exams'
  match '/userpanel/:user_id' => 'pages#userpanel'

  resources :users do
    resource :profile
    resources :evaluations do
      resources :details
    end
    resources :postural_assessments
    resources :exams
  end

  root to: 'pages#home'
end

app/models/postural_assessment.rb
class PosturalAssessment < ActiveRecord::Base
  belongs_to :user
  attr_accessible :artrose, :cifose, :escoliose, :hernia, :image1, :image2, :image3, :lordose, :obs, :dataeval
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader

end

app/controllers/postural_assessments_controller.rb
# encoding: utf-8

class PosturalAssessmentsController < ApplicationController

	def new
		@user = User.find(params[:user_id])
		@postural_assessment = PosturalAssessment.new
		@postural_assessment.build_user
	end

	def create
		@user = User.find(params[:user_id])
		@postural_assessment = @user.postural_assessments.new(params[:postural_assessment])
		if @postural_assessment.save
			redirect_to user_postural_assessment_path(@user, @postural_assessment), notice: 'Avaliação postural criada com sucesso!'
		else
			render :action => "new"
		end
	end

	def show
		@user = User.find(params[:user_id])
		@postural_assessment = @user.postural_assessments.find(params[:id])		
	end

	def edit
		@user = User.find(params[:user_id])
		@postural_assessment = @user.postural_assessments.find(params[:id])		
	end

	def index
		@user = User.find(params[:user_id])
		@postural_assessment = @user.postural_assessments.all	
	end

	def update
		@user = User.find(params[:user_id])
		@postural_assessment = @user.postural_assessments.find(params[:id])

		if @postural_assessment.update_attributes(params[:postural_assessment])
			redirect_to user_postural_assessment_path(@user, @postural_assessment), notice: 'Avaliação postural alterada com sucesso!'
		else
			render :action => "edit"
		end
	end
end

app/helpers/postural_assessments_helper.rb
module PosturalAssessmentsHelper
end

app/views/postural_assessments/_form.html.erb
<%= form_for [current_user,@postural_assessment], :html => {:multipart => true} do |f| %>
  <%= f.label :dataeval, "Data da Avaliação:" %> <br>
    <%= f.date_select(:dataeval, :order => [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'], :start_year => Time.now.year - 6, :end_year => Time.now.year) %>
  <p>Marque abaixo os poblemas posturais e de coluna encontrados:</p>
  <p>
  	<%= f.label :cifose, "Cifose" %>
  	<%= f.check_box :cifose %>
  </p>
  <p>
  	<%= f.label :Lordose, "Lordose" %>
  	<%= f.check_box :lordose %>
  </p>
  <p>
  	<%= f.label :Escoliose, "Escoliose" %>
  	<%= f.check_box :escoliose %>
  </p>
  <p>
  	<%= f.label :Artrose, "Artrose" %>
  	<%= f.check_box :artrose %>
  </p>
  <p>
  	<%= f.label :hernia, "Hérnia De Disco" %>
  	<%= f.check_box :hernia %>
  </p>
  <p>
  	<%= f.label :obs, "Observações Adicionais:" %><br>
  	<%= f.text_area :obs %>
  </p>
  <p>Agora selecione as fotos com a análise postural do aluno:</p>
  <p>
  	<%= f.label :frontal, "Foto Frontal:" %>
  	<%= f.file_field :image1 %>
  </p>
  <p>
  	<%= f.label :lateral, "Foto Lateral:" %>
  	<%= f.file_field :image2 %>
  </p>
  <p>
  	<%= f.label :traseira, "Foto Costas:" %>
  	<%= f.file_field :image3 %>
  </p>

  <div class="actions">
    <%= f.submit "Enviar", disable_with: 'Enviando...' %>
  </div>

<% end %>

app/views/postural_assessments/edit.html.erb
<h1>Editar Avaliação Postural</h1>

<%= render 'form' %>

<%= link_to 'Voltar', user_postural_assessment_path(current_user,@postural_assessment) %>

app/views/postural_assessments/index.html.erb
<h1>Lista de Avaliações Posturais</h1>
<p class="justified">Aqui estão arquivadas todas as avaliações posturais cadastradas em nosso sistema. Arquivadas, você poderá sempre conferir sua condição física em avaliações anteriores.</p>
<% for postural_assessment in @postural_assessments %>
	<p>
		<b>Data da Avaliação:</b>
		<%= postural_assessment.dataeval %>
	</p>
	<p> 
		<%= link_to 'Leia Mais...', user_postural_assessment_path(@user,postural_assessment)%> | <%= link_to 'Editar', edit_user_postural_assessment_path(@user,postural_assessment)%>
	</p>
<% end %>
<%= link_to 'Nova Avaliação Física', new_user_postural_assessment_path(@user) %>

app/views/postural_assessments/new.html.erb
<h1>Criação de Avaliação Postural</h1>
	
	<%= render 'form' %>

<%= link_to 'Voltar', user_path(@user) %>

app/views/postural_assessments/show.html.erb
<h1>Avaliação Postural</h1>

<h3>Problemas Posturais encontrados:</h3>

<% if @postural_assessment.cifose %>
	<p>Cifose</p> <br>
<% end %>

<% if @postural_assessment.lordose %>
	<p>Lordose</p> <br>
<% end %>

<% if @postural_assessment.escoliose %>
	<p>Escoliose</p> <br>
<% end %>

<h3>Problemas na Coluna:</h3>

<% if @postural_assessment.artrose %>
	<p>Artrose</p> <br>
<% end %>

<% if @postural_assessment.hernia %>
	<p>Hérnia de Disco</p> <br>
<% end %>

<h3>Observações:</h3>

<% if !@postural_assessment.obs.blank? %>
	<p><%= @postural_assessment.obs%></p>
<% end %>

<h3>Fotos do Aluno:</h3>

<%= image_tag @postural_assessment.image1_url(:thumb) if @postural_assessment.image1? %>

<%= image_tag @postural_assessment.image2_url(:thumb) if @postural_assessment.image2? %>

<%= image_tag @postural_assessment.image3_url(:thumb) if @postural_assessment.image3? %>

<br>

<%= link_to 'Editar', edit_user_postural_assessment_path(current_user,@postural_assessment)  %> | <%= link_to 'Voltar', user_postural_assessments_path(current_user) %>